### ISSUE TITLE
Not working no response no error

### ISSUE THREAD

**Issue by iphone201988** [iMicknl/cordova-plugin-openalpr#47]
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 3.0.0, (and 16 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.15.1 (/usr/local/bin/node)
   npm        : 6.7.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61

**Comment by iphone201988** [comment]
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.8
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 3.0.0, (and 16 other plugins)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v10.15.1 (/usr/local/bin/node)
   npm        : 6.7.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61

**Comment by iphone201988** [comment]
W/Activity: Slow Operation: Activity com.velosum.vcitemobile/.MainActivity onActivityResult took 666ms
W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/base.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/lib/arm64, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/base.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.velosum.vcitemobile-r34ztNGLV5GECo5JZ4OPdA==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libopenalprjni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.openalpr.jni.Alpr.<clinit>(Alpr.java:9)
        at org.apache.cordova.openalpr.OpenALPR.initAlpr(OpenALPR.java:170)
        at org.apache.cordova.openalpr.OpenALPR.scan(OpenALPR.java:114)
        at org.apache.cordova.openalpr.OpenALPR.execute(OpenALPR.java:44)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:181)
        at android.os.HandlerThread.run(HandlerThread.java:67)
W/System: A resource failed to call close. 
Application terminated.

**Comment by iphone201988** [comment]
I find the solution. 
/platforms/android/app/build.gradle open the fine and paste the line "ndk {  abiFilters "armeabi-v7a" }"

Eg: 
android {
                .........
    defaultConfig {
                      ....
        }
        ndk {
            abiFilters "armeabi-v7a"
        }
    }
